# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-18 21:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('state', models.CharField(choices=[('Released', 'Released'), ('Locked', 'Locked'), ('Captured', 'Captured')], default='Locked', max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='bank.Account', to_field='eid')),
            ],
            options={
                'verbose_name': 'Authorization',
                'verbose_name_plural': 'Authorizations',
            },
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='bank.Account', to_field='eid')),
            ],
            options={
                'verbose_name': 'Capture',
                'verbose_name_plural': 'Captures',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='bank.Account', to_field='eid')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('comments', models.TextField()),
                ('transaction_type', models.CharField(choices=[('Transfer', 'Transfer'), ('Authorization', 'Authorization'), ('Capture', 'Capture'), ('Deposit', 'Deposit')], default='Transfer', max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank.Account')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('comments', models.TextField()),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to='bank.Account', to_field='eid')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_sent', to='bank.Account', to_field='eid')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
            },
        ),
    ]
